export const homeObjOne = {
  lightBg: false,
  primary: true,
  imgStart: "",
  topLine: "marketing agency",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  buttonLabel: "Get Started",
  description: "description goes here",
  headline: "Headline",
  img: require("../../images/Box_3.0_TAN.svg"),
  alt: "Image Alt",
  start: "",
};

export const homeObjTwo = {
  lightBg: true,
  primary: false,
  imgStart: "start",
  topLine: "marketing agency",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  buttonLabel: "Get Started",
  description: "description goes here",
  headline: "Headline",
  img: require("../../images/Box_3.0_TAN.svg"),
  alt: "Image Alt",
  start: "true",
};

export const homeObjThree = {
  lightBg: false,
  primary: true,
  imgStart: "",
  topLine: "marketing agency",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  buttonLabel: "Get Started",
  description: "description goes here",
  headline: "Headline",
  img: require("../../images/Box_3.0_TAN.svg"),
  alt: "Image Alt",
  start: "",
};

export const homeObjFour = {
  lightBg: false,
  primary: true,
  imgStart: "",
  topLine: "marketing agency",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  buttonLabel: "Get Started",
  description: "description goes here",
  headline: "Headline",
  img: require("../../images/Box_3.0_TAN.svg"),
  alt: "Image Alt",
  start: "",
};
